name: polymerjs
version: 0.0.1
author: Kasper Peulen <kasperpeulen@gmail.com>
description: Dart wrapper for polymer js 1.0.
homepage: https://github.com/kasperpeulen/polymerjs-dart
environment:
  sdk: '<2.0.0'
dev_dependencies:
  test: ^0.12.3+2
  grinder: ^0.7.1+3
